# Generated by Django 5.0.6 on 2024-05-24 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_status",
                    models.BooleanField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Area Active Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Creation Date & Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updation Date & Time"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Area Name"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Priority"
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_status",
                    models.BooleanField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Area Active Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Creation Date & Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updation Date & Time"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="State Name"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        limit_choices_to={"active_status": "1"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="State_state",
                        to="area.area",
                        verbose_name="Area",
                    ),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "State",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_status",
                    models.BooleanField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Area Active Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Creation Date & Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updation Date & Time"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="City Name"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        limit_choices_to={"active_status": "1"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="City_city",
                        to="area.state",
                        verbose_name="State",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "City",
            },
        ),
    ]
