# Generated by Django 5.0.6 on 2024-05-24 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("area", "0001_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EndUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True, null=True, verbose_name="End User Avatar"
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="End User Age"
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Is end user banned ?",
                    ),
                ),
                (
                    "active_status",
                    models.BooleanField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="End User Active Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Creation Date & Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updation Date & Time"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="View Count"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enduser_area",
                        to="area.area",
                        verbose_name="Area",
                    ),
                ),
                (
                    "auth_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enduser_auth_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auth User",
                    ),
                ),
            ],
            options={
                "verbose_name": "End User",
                "verbose_name_plural": "End Users",
            },
        ),
        migrations.CreateModel(
            name="ShopOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Shop Owner Name"),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Shop Owner Email",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/",
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "active_status",
                    models.BooleanField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Shop Owner Active Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Creation Date & Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updation Date & Time"
                    ),
                ),
                (
                    "auth_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopowner_auth_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Shop Owner",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopowner_shop",
                        to="shops.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Owner",
                "verbose_name_plural": "Shop Owners",
            },
        ),
    ]
