# Generated by Django 5.0.6 on 2024-05-24 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("area", "0001_initial"),
        ("genre", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Shop Name"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Url"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Shop Address",
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shops/",
                        verbose_name="Shop Profile Photo",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shops/",
                        verbose_name="Shop Banner Photo",
                    ),
                ),
                (
                    "bio",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Shop Bio"
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Shop Opening Time"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Shop Closing Time"
                    ),
                ),
                (
                    "is_24hr_open",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Is Shop 24hr Open",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Mobile No"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Comment"
                    ),
                ),
                (
                    "staff_attitude_rating",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Shop Staff Attitude Rating",
                    ),
                ),
                (
                    "pay_rating",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Shop Pay Rating",
                    ),
                ),
                (
                    "user_rating",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Shop User Rating",
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Review Count"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="View Count"
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Is Premium Member",
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        blank=True, default=0, null=True, verbose_name="Is Shop Banned"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_city",
                        to="area.city",
                        verbose_name="Shop City",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_genre",
                        to="genre.genre",
                        verbose_name="Shop Genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Question")),
                ("answer", models.CharField(max_length=500, verbose_name="Answer")),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_shop",
                        to="shops.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ for Shop",
                "verbose_name_plural": "FAQ for shops",
            },
        ),
    ]
