# Generated by Django 5.2.3 on 2025-06-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_statis', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Date & Time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
