# Generated by Django 5.2.3 on 2025-06-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Area Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
    ]
