# Generated by Django 5.2 on 2025-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_brand_college_skills_products_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("salary", models.FloatField()),
                ("dept", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
