# Generated by Django 5.2 on 2025-04-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
