# Generated by Django 5.2 on 2025-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
